secret_key_base: RIlFoXYBELyEbbhJcD6NkxIJWFeMic7v6m7iKd0nO5o
port: 3000
name: g_tree

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:postgres@localhost:5432/amber_tree_development
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
